### DISCUSSION TITLE
pico.colors helpers to change entire theme

### DISCUSSION THREAD

**Discussion by odama626** [Yohn/PicoCSS#28] [Ideas]
I recently wanted to make success / error buttons and think it would be really useful to switch colors on the fly when using pico.colors.css

something like

.pico-color-red on a component -- and it updates all the css variables to change the theme to that color.

I was messing around with chatgpt and think I got an accurate jade color

```css
.pico-color-jade {
  --pico-primary-background: var(--pico-color-jade-550); /* Jade 550 */
  --pico-primary-hover-background: var(--pico-color-jade-600); /* Jade 600 */
  --pico-primary-hover: var(--pico-color-jade-650); /* Jade 650 */
  --pico-primary-border: var(--pico-color-jade-550); /* Border color matches primary background */
  --pico-primary-hover-border: var(--pico-color-jade-600); /* Border color matches hover background */
  --pico-primary-focus: rgba(0, 166, 110, 0.5); /* Focus color directly */
  --pico-primary-inverse: var(--pico-color-light); /* Light color */
}

/* Dark mode styles */
@media (prefers-color-scheme: dark) {
  :not([data-theme]).pico-color-jade {
    --pico-primary-background: var(--pico-color-jade-550); /* Jade 550 */
    --pico-primary-hover-background: var(--pico-color-jade-500); /* Jade 500 */
    --pico-primary-hover: var(--pico-color-jade-250); /* Jade 250 */
    --pico-primary-border: var(--pico-color-jade-550); /* Border color matches primary background */
    --pico-primary-hover-border: var(--pico-color-jade-500); /* Border color matches hover background */
    --pico-primary-focus: rgba(0, 180, 120, 0.375); /* Focus color directly */
    --pico-primary-inverse: var(--pico-color-light); /* Light color */
  }
}

[data-theme="dark"] .pico-color-jade {
  --pico-primary-background: var(--pico-color-jade-550); /* Jade 550 */
  --pico-primary-hover-background: var(--pico-color-jade-500); /* Jade 500 */
  --pico-primary-hover: var(--pico-color-jade-250); /* Jade 250 */
  --pico-primary-border: var(--pico-color-jade-550); /* Border color matches primary background */
  --pico-primary-hover-border: var(--pico-color-jade-500); /* Border color matches hover background */
  --pico-primary-focus: rgba(0, 180, 120, 0.375); /* Focus color directly */
  --pico-primary-inverse: var(--pico-color-light); /* Light color */
}
```
