### DISCUSSION TITLE
button.ghost

### DISCUSSION THREAD

**Discussion by odama626** [Yohn/PicoCSS#29] [Ideas]
a ghost style button that is like outline -- just without the outline

messing around with chatgpt...

```css
/* Base ghost button style */
:is(button, [type="button"], [type="submit"], [role="button"]).ghost {
  --pico-background-color: transparent;
  --pico-border-color: transparent;
  --pico-color: var(--pico-primary);
}

/* Hover, focus, active, and aria-current states */
:is(button, [type="button"], [type="submit"], [role="button"]).ghost:is(
    :hover,
    :focus,
    :active,
    [aria-current]:not([aria-current="false"])
  ) {
  --pico-background-color: transparent;
  --pico-color: var(--pico-primary-hover);
  --pico-border-color: transparent;
}

/* Secondary ghost button */
:is(button, [type="button"], [type="submit"], [role="button"]).ghost.secondary {
  --pico-color: var(--pico-secondary);
}

:is(button, [type="button"], [type="submit"], [role="button"]).ghost.secondary:is(
    :hover,
    :focus,
    :active,
    [aria-current]:not([aria-current="false"])
  ) {
  --pico-color: var(--pico-secondary-hover);
}

/* Contrast ghost button */
:is(button, [type="button"], [type="submit"], [role="button"]).ghost.contrast {
  --pico-color: var(--pico-contrast);
}

:is(button, [type="button"], [type="submit"], [role="button"]).ghost.contrast:is(
    :hover,
    :focus,
    :active,
    [aria-current]:not([aria-current="false"])
  ) {
  --pico-color: var(--pico-contrast-hover);
}
```
