### DISCUSSION TITLE
A context menu

### DISCUSSION THREAD

**Discussion by odama626** [Yohn/PicoCSS#39] [Ideas]
In my local code I am using dropdown to make a context menu, and I think it could be useful

![image](https://github.com/user-attachments/assets/84bcc913-4570-4ddb-a652-7e49f3fa61c1)

```scss
.dropdown.context-menu {
  margin: 0;
  &.left {
    ul {
      direction: ltr;
      overflow: hidden;
    }
  }

  summary {
    background-color: transparent !important;
    border: none !important;

    &:after {
      content: none;
    }
  }

  hr {
    margin: calc(var(--pico-form-element-spacing-vertical) * 0.5) var(--pico-spacing);
  }

  li {
    &:has(button) {
      padding: 0;
    }

    button {
      color: var(--pico-dropdown-color);
      width: 100%;
    }

    > a {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: var(--pico-form-element-spacing-vertical) var(--pico-form-element-spacing-horizontal);
    }

    &:hover {
      background: var(--pico-dropdown-hover-background-color);
      color: var(--pico-dropdown-hover);
    }
  }
}
```

```
<details class='dropdown context-menu left'>
  <summary id='overflowMenuTrigger'>
    <MenuIcon />
  </summary>
  <ul dir='rtl'>
    <li>
      <button class='icon ghost' onClick={() => createInviteLink(params.id)}>
        <CopyInviteLinkIcon /> Copy Invite Link
      </button>
    </li>
    <li>
      <button class='icon ghost' onClick={() => setOpenModal('collaborators')}>
        <CollaboratorsIcon /> Collaborators
      </button>
    </li>
    <hr />
    <li>
      <A href='/user/account'>
        <AccountIcon /> Account Settings
      </A>
    </li>
  </ul>
</details>
```
