### DISCUSSION TITLE
Add an official alert/flash component

### DISCUSSION THREAD

**Discussion by anthony-robin** [Yohn/PicoCSS#40] [Ideas]
Currently, there is no alert/flash component working out of the box.

![image](https://github.com/user-attachments/assets/01a09e5e-cf0c-404a-9537-e3eba281e59d)

An experiment was made with `v1.x` on this [Codepen](https://codepen.io/mjau-mjau/pen/xxjZRGg) but it does not work anymore with `v2.x`.

Here is the original issue on the main repo asking for alert/flash: https://github.com/picocss/pico/issues/12

What do you think about this new component ?

**Comment by Yohn** [comment]
Yeah, I would like to have an alert type role in place for PicoCSS. 

[role="alert" docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role)

I'm completely open for a pull request as long as we're following the guidelines in the docs above to some degree. 

The codepen definitely has a good starting point to work off of, we should use the v2 variables instead of creating more that have the same values. 

For the green and red colors, I'd like to use the [del and ins](https://picocss.com/docs/typography#inline-text-elements) colors, for both dark and light modes. Not sure about a warning or info colors, we'll have to investigate what color codes are used within the [pico colors](https://picocss.com/docs/colors). 

This would also be good to work as a classless alert, so a default alert color scheme without classes, and then for more robust alert we could add the classes. Maybe there's an aria attribute that can be used instead of classes for the different type of alerts.

From the docs:

> The alert role is of the five live region roles. Dynamic changes that are less urgent should use a less aggressive method, such as including aria-live="polite" or using an other live region role like status. If the user is expected to close the alert, then the alertdialog role should be used instead.

**Comment by Yohn** [comment]
Something like the following for a default, classless alert may work.

```css
[role="alert"] {
	background-color: var(--pico-primary-focus);
	display: block;
	padding: calc(var(--pico-spacing) * 0.5);
	margin-block-start: calc(var(--pico-spacing) * 0.5);
	border-radius: var(--pico-border-radius);
	border: var(--pico-border-width) solid var(--pico-primary);
	color: var(--pico-primary-inverse);
}
```

![image](https://github.com/user-attachments/assets/86c747a7-612e-40ad-879e-3f95e7096445)

![image](https://github.com/user-attachments/assets/8b6e817a-93f1-4c9f-b69c-27c882a062a8)
